// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZG85l6w-qt4IgokdlG1YA4P0eghC3O0',
    appId: '1:440100469243:web:fe5cca568f691ba688335e',
    messagingSenderId: '440100469243',
    projectId: 'socialmediademo-5ec98',
    authDomain: 'socialmediademo-5ec98.firebaseapp.com',
    storageBucket: 'socialmediademo-5ec98.firebasestorage.app',
    measurementId: 'G-K7383KQC1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-vgcImee-OTxjIB9BXW2YBHg8LDBEjok',
    appId: '1:440100469243:android:4f308c2b212064db88335e',
    messagingSenderId: '440100469243',
    projectId: 'socialmediademo-5ec98',
    storageBucket: 'socialmediademo-5ec98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDC8iMwKJbQFfBrJ54EKtGW2eHYjnPens',
    appId: '1:440100469243:ios:3ad9bfa21bf4abbd88335e',
    messagingSenderId: '440100469243',
    projectId: 'socialmediademo-5ec98',
    storageBucket: 'socialmediademo-5ec98.firebasestorage.app',
    iosBundleId: 'com.example.socialDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDC8iMwKJbQFfBrJ54EKtGW2eHYjnPens',
    appId: '1:440100469243:ios:3ad9bfa21bf4abbd88335e',
    messagingSenderId: '440100469243',
    projectId: 'socialmediademo-5ec98',
    storageBucket: 'socialmediademo-5ec98.firebasestorage.app',
    iosBundleId: 'com.example.socialDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrZG85l6w-qt4IgokdlG1YA4P0eghC3O0',
    appId: '1:440100469243:web:c2d0f09d27057ac888335e',
    messagingSenderId: '440100469243',
    projectId: 'socialmediademo-5ec98',
    authDomain: 'socialmediademo-5ec98.firebaseapp.com',
    storageBucket: 'socialmediademo-5ec98.firebasestorage.app',
    measurementId: 'G-TR26DN4R0R',
  );
}
